<?php
return [
   [
        "idDrink"           =>"17825",
        "strDrink"          =>"Brigadier",
        "strCategory"       =>"Cocktail",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Coupe Glass",
        "strInstructions"   =>"Mix ingredients in a warmed mug and stir.",
        "strInstructionsIT" =>"Mescolare gli ingredienti in una tazza calda e mescola.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/nl89tf1518947401.jpg",
   ],
   [
        "idDrink"           =>"12780",
        "strDrink"          =>"Spiking coffee",
        "strCategory"       =>"Coffee \/ Tea",
        "strAlcoholic"      =>"Non alcoholic",
        "strGlass"          =>"Coffee mug",
        "strInstructions"   =>"Incidentally, a pinch of cinnamon is indeed a nice addition to coffee but true heaven is a cardamom seed. Of course, you serve it in a coffee mug.",
        "strInstructionsIT" =>"Per inciso, un pizzico di cannella \u00e8 davvero una bella aggiunta al caff\u00e8. Servire in una tazza da caff\u00e8.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/isql6y1487602375.jpg",
   ],
   [
        "idDrink"           =>"17060",
        "strDrink"          =>"24k nightmare",
        "strCategory"       =>"Shot",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Shot glass",
        "strInstructions"   =>"Add over ice,shake and pour.",
        "strInstructionsIT" =>"Aggiungere gli ingredienti dopo aver versato un po\u2019 di ghiaccio, agitare e versare.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/yyrwty1468877498.jpg"
   ],
   [
        "idDrink"           =>"12474",
        "strDrink"          =>"Waikiki Beachcomber",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Shake all ingredients with ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT" =>"Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/ysuqus1441208583.jpg",
   ],
   [
        "idDrink"           =>"12196",
        "strDrink"          =>"Sidecar",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Pour all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass.",
        "strInstructionsIT" =>"Versare tutti gli ingredienti in uno shaker pieno di ghiaccio.Shakerare bene e filtrare nella coppetta da cocktail.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/x72sik1606854964.jpg",
   ],
   [
        "idDrink"           =>"17216",
        "strDrink"          =>"Tommy's Margarita",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Old-Fashioned glass",
        "strInstructions"   =>"Shake and strain into a chilled cocktail glass.",
        "strInstructionsIT" =>"Shakerare e filtrare in una coppetta da cocktail ghiacciata.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/loezxn1504373874.jpg",
   ],
   [
        "idDrink"           =>"11028",
        "strDrink"          =>"Amaretto Stinger",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Shake ingredients well with cracked ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT" =>"Shakerare bene gli ingredienti con ghiaccio tritato, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/vvop4w1493069934.jpg",
   ],
   [
        "idDrink"           =>"11024",
        "strDrink"          =>"Almond Joy",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"     =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Shake all ingredients with ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT" =>"Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/xutuqs1483388296.jpg",
   ],
   [
        "idDrink"           =>"13389",
        "strDrink"          =>"Snake Bite (UK)",
        "strCategory"       =>"Beer",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Pint glass",
        "strInstructions"   =>"Pour ingredients into a pint glass. Drink. Fall over.",
        "strInstructionsIT" =>"Versare gli ingredienti in un bicchiere da pinta.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/xuwpyu1441248734.jpg",
   ],
   [
        "idDrink"           =>"11055",
        "strDrink"          =>"Artillery",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Stir all ingredients with ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT" =>"Mescolare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/g1vnbe1493067747.jpg",
   ],
   [
        "idDrink"           =>"17233",
        "strDrink"          =>"Salted Toffee Martini",
        "strCategory"       =>"Cocktail",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Add ice, toffee gin, chocolate liqueur and Amaretto to a cocktail shaker and shake vigorously. \r\nPour the chocolate syrup into a saucer and dip the top of a martini glass into the sauce. Grate some of the Willie\\'s sea salt chocolate into another saucer and dip the coated glass, so the flakes stick to the sauce, creating a chocolate rim!\r\nPour the contents of the shaker into your chocolatey glass and sprinkle with more grated chocolate - enjoy!  ",
        "strInstructionsIT" =>"Aggiungere ghiaccio, gin, liquore al cioccolato e amaretto in uno shaker e agitare energicamente.\r\nVersare lo sciroppo di cioccolato in un piattino e immergere la parte superiore di un bicchiere da martini nella salsa.\r\nGrattugiare un po 'di cioccolato al sale marino in un altro piattino e immergere il vetro rivestito, in modo che i fiocchi si attacchino alla salsa, creando un bordo di cioccolato! Versare il contenuto dello shaker nel bicchiere cioccolatoso e cospargere con altro cioccolato grattugiato - buon divertimento!",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/3s6mlr1509551211.jpg",
   ],
   [
        "idDrink"           =>"178311",
        "strDrink"          =>"Broadside",
        "strCategory"       =>"Cocktail",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Highball glass",
        "strInstructions"   =>"Half fill the glass with ice cubes. Crush the wormwood and add to ice. Pour rum, scotch and butters, then serve!",
        "strInstructionsIT" =>"Riempire a met\u00e0 il bicchiere con cubetti di ghiaccio. Schiacciare l'assenzio e aggiungerlo al ghiaccio. Versare rum, scotch e burro, quindi servire!",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/l2o6xu1582476870.jpg",
    ],
    [
        "idDrink"           =>"11016",
        "strDrink"          =>"Brandy Alexander",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Whiskey Glass",
        "strInstructions"   =>"Shake all ingredients (except nutmeg) with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.",
        "strInstructionsIT" =>"Shakerare tutti gli ingredienti (tranne la noce moscata) con ghiaccio e filtrare il contenuto in una coppetta da cocktail. Cospargere di noce moscata e servire.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/mlyk1i1606772340.jpg"
    ],
    [
        "idDrink"           =>"12528",
        "strDrink"          =>"White Russian",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Old-fashioned glass",
        "strInstructions"   =>"Pour vodka and coffee liqueur over ice cubes in an old-fashioned glass. Fill with light cream and serve.",
        "strInstructionsIT" =>"Versare la vodka e il liquore al caff\u00e8 sui cubetti di ghiaccio in un bicchiere vecchio stile.Farcite con crema leggera e servite",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/vsrupw1472405732.jpg"
    ],
    [
        "idDrink"           =>"13936",
        "strDrink"          =>"Miami Vice",
        "strCategory"       =>"Cocktail",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"First: Mix pina colada with 2.5 oz. of rum with ice(set aside). Second: Mix daiquiri with 2.5 oz. of rum with ice. Third: While frozen, add pina colda mix then daiquiri mix in glass (Making sure they do not get mixed together).",
        "strInstructionsIT" =>"Primo: mescola la pina colada con 75ml di rum con ghiaccio (mettere da parte).\r\nSecondo: mescola daiquiri con 75ml di rum con ghiaccio.\r\nTerzo: mentre \u00e8 freddo, aggiungi il mix di pina colada e poi i daiquiri nel bicchiere (assicurandoti che non si mescolino insieme).",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/qvuyqw1441208955.jpg"
    ],
    [
        "idDrink"           =>"17267",
        "strDrink"          =>"Bahama Mama",
        "strCategory"       =>"Cocktail",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Highball glass",
        "strInstructions"   =>"Add 2 parts club soda or more or less to taste.\r\n\r\nMix it all together and pour over a bunch of ice. Drink with a straw.","strInstructionsIT" =>"Aggiungere 2 bicchieri da shot con acqua di selt.\r\nMescola il tutto e versa sopra un po 'di ghiaccio.\r\nBevi con una cannuccia.","strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/tyb4a41515793339.jpg"
    ],
    [
        "idDrink"           =>"13020",
        "strDrink"          =>"Sangria",
        "strCategory"       =>"Punch \/ Party Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Pitcher",
        "strInstructions"   =>"Mix all together in a pitcher and refrigerate. Add cloves and cinnamon sticks to taste. Serve in wine glasses.",
        "strInstructionsIT" =>"Mescolare il tutto in una brocca e conservare in frigorifero.\r\nAggiungere i chiodi di garofano e le stecche di cannella a piacere.\r\nServire in calici da vino.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/xrvxpp1441249280.jpg",
    ],
    [
        "idDrink"           =>"12562",
        "strDrink"          =>"Alice Cocktail",
        "strCategory"       =>"Cocktail",
        "strAlcoholic"      =>"Non alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Shake well, strain into a large cocktail glass.",
        "strInstructionsIT" =>"Shakerare bene, filtrare in una coppetta da cocktail capiente.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/qyqtpv1468876144.jpg"
    ],
    [
        "idDrink"           =>"11120",
        "strDrink"          =>"Bluebird",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"In a mixing glass half-filled with crushed ice, combine the gin, triple sec, Curacao, and bitters. Stir well. Strain into a cocktail glass and garnish with the lemon twist and the cherry.",
        "strInstructionsIT" =>"In un mixing glass riempito a met\u00e0 con ghiaccio tritato, unisci il gin, il triple sec, il Curacao e il bitter.Mescolare bene.Filtrare in una coppetta da cocktail e guarnire con la scorza di limone e la ciliegia.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/5jhyd01582579843.jpg",
    ],
    [
        "idDrink"           =>"11423",
        "strDrink"          =>"Godfather",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Old-fashioned glass",
        "strInstructions"   =>"Pour all ingredients directly into old fashioned glass filled with ice cubes. Stir gently.",
        "strInstructionsIT" =>"Versare tutti gli ingredienti direttamente nel bicchiere vecchio stile riempito di cubetti di ghiaccio. Mescola delicatamente.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/e5zgao1582582378.jpg",
    ],
    [
        "idDrink"           =>"17220",
        "strDrink"          =>"Butter Baby",
        "strCategory"       =>"Shake",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Beer mug",
        "strInstructions"   =>"Blend together in a blender. Serve in a chilled Beer mug with Fresh Blueberries and caramel for topping.",
        "strInstructionsIT" =>"Mescola insieme in un frullatore.\r\nServire in un boccale di birra freddo con mirtilli freschi e caramello per guarnire.","strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/1xhjk91504783763.jpg"
    ],
    [
        "idDrink"           =>"11983",
        "strDrink"          =>"Quaker's Cocktail",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Cocktail glass",
        "strInstructions"   =>"Shake all ingredients with ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT" =>"Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/yrqppx1478962314.jpg"
    ],
    [
        "idDrink"           =>"178365",
        "strDrink"          =>"Gin Tonic",
        "strCategory"       =>"Cocktail",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Highball glass",
        "strInstructions"   =>"Fill a highball glass with ice, pour the gin, top with tonic water and squeeze a lemon wedge and garnish with a lemon wedge.","strInstructionsIT" =>"Colmate un bicchiere highball di ghiaccio, versate il gin, colmate con acqua tonica e spremete uno spicchio di limone e guarnite con una fetta di limone. ",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/qcgz0t1643821443.jpg",
    ],
    [
        "idDrink"           =>"12782",
        "strDrink"          =>"Thai Coffee",
        "strCategory"       =>"Coffee \/ Tea",
        "strAlcoholic"      =>"Non alcoholic",
        "strGlass"          =>"Highball glass",
        "strInstructions"   =>"Place the coffee and spices in the filter cone of your coffee maker. Brew coffee as usual, let it cool. In a tall glass, dissolve 1 or 2 teaspoons of sugar in an ounce of the coffee (it's easier to dissolve than if you put it right over ice). Add 5-6 ice cubes and pour coffee to within about 1 inch of the top of the glass. Rest a spoon on top of the coffee and slowly pour whipping cream into the spoon. This will make the cream float on top of the coffee rather than dispersing into it right away.",
        "strInstructionsIT" =>"Metti il caff\u00e8 e le spezie nel cono del filtro della tua caffettiera.\r\nPrepara il caff\u00e8 come al solito, lascialo raffreddare.\r\nIn un bicchiere alto, sciogli 1 o 2 cucchiaini di zucchero in 30gr di caff\u00e8 (\u00e8 pi\u00f9 facile da sciogliere che se lo metti sul ghiaccio).\r\nAggiungere 5-6 cubetti di ghiaccio e versare il caff\u00e8 a circa 1 pollice dalla parte superiore del bicchiere.\r\nAppoggia un cucchiaio sopra il caff\u00e8 e versa lentamente la panna montata nel cucchiaio.\r\nIn questo modo la crema gallegger\u00e0 sul caff\u00e8 anzich\u00e9 disperdersi subito.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/wquwxs1441247025.jpg"
    ],
    [
        "idDrink"           =>"11396",
        "strDrink"          =>"Gentleman's Club",
        "strCategory"       =>"Ordinary Drink",
        "strAlcoholic"      =>"Alcoholic",
        "strGlass"          =>"Old-fashioned glass",
        "strInstructions"   =>"In an old-fashioned glass almost filled with ice cubes, combine all of the ingredients. Stir well.",
        "strInstructionsIT" =>"In un bicchiere vecchio stile quasi pieno di cubetti di ghiaccio, unisci tutti gli ingredienti. Mescolare bene.",
        "strDrinkThumb"     =>"https:\/\/www.thecocktaildb.com\/images\/media\/drink\/k2r7wv1582481454.jpg"
    ],

];